---
# Set up http/https proxy settings

- block:

  - name: Set apt proxy http
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    copy:
      dest: "/etc/apt/apt.conf.d/99-proxy-http"
      content: "Acquire::http::proxy \"{{ http_proxy }}\";"

  - name: Set apt proxy https
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    copy:
      dest: "/etc/apt/apt.conf.d/99-proxy-https"
      content: "Acquire::https::proxy \"{{ http_proxy }}\";"

  - name: Ensure root/.pip directory exists, required to configure pip
    file:
      dest: "/root/.pip/"
      state: directory

  - name: Set pip proxy
    ini_file:
      dest: "/root/.pip/pip.conf"
      section: "global"
      option: "proxy"
      value: "{{ http_proxy }}"
      state: present

  when: use_local_proxy

# Remove up http/https proxy settings

- block:

  - name: Remove apt proxy http
    file:
      dest: "/etc/apt/apt.conf.d/99-proxy-http"
      state: absent
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Remove apt proxy https
    file:
      dest: "/etc/apt/apt.conf.d/99-proxy-https"
      state: absent
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Ensure root/.pip directory exists, required to configure pip
    file:
      dest: "/root/.pip/"
      state: directory

  - name: Remove pip proxy to be
    ini_file:
      dest: "/root/.pip/pip.conf"
      section: "global"
      option: "proxy"
      value: "{{ http_proxy }}"
      state: absent

  when: not use_local_proxy
