---
- name: apt update
  when: ansible_os_family == 'Debian'
  apt:
    upgrade: no
    update_cache: yes
    cache_valid_time: 3600
  retries: "{{ apt_retries }}"

- name: Install required system packages (ubuntu)
  when: ansible_os_family == 'Debian'
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - python-simplejson
    - aptitude
